#goal definition

geometry_msgs/TransformStamped desired_transform

float64[6] stage1_kp
float64[6] stage2_kp
float64[6] stage3_kp

float64 stage1_tol_p
float64 stage1_tol_r
float64 stage2_tol_p
float64 stage2_tol_r
float64 stage3_tol_p
float64 stage3_tol_r

float64 stage2_z_offset

geometry_msgs/Wrench abort_force
geometry_msgs/Wrench placement_force
float64[6] force_ki

---
#result definition

string error_msg
---
#feedback

